/*Tabelas

CAMP_CARDIOLOGIA 
CAMP_CHECKUP_SAUDE 
CAMP_CHECKUP_HOMEM
CAMP_CHECKUP_MULHER
CAMP_ODONTO
CAMP_OFTALMOLOGIA
CAMP_PSICO_PSIQUI
CAMP_ODONTO_GERAL
CAMP_DERMATOLOGIA 
CAMP_ORTODONTIA

VIEW_CAMP_CARDIOLOGIA
VIEW_CAMP_CHECKUP_SAUDE
VIEW_CAMP_CHECKUP_HOMEM
VIEW_CAMP_CHECKUP_MULHER
VIEW_CAMP_ODONTO
VIEW_CAMP_OFTALMOLOGIA
VIEW_CAMP_PSICO_PSIQUI
VIEW_CAMP_ODONTO_GERAL
VIEW_CAMP_DERMATOLOGIA

 */

 
 -- Conceder permissões para o usuário SISNET nas tabelas
  GRANT SELECT ON "AGE"."CAMP_DERMATOLOGIA" TO "CONTROL";
  GRANT INSERT ON "AGE"."CAMP_DERMATOLOGIA" TO "SISNET";
  GRANT SELECT ON "AGE"."CAMP_DERMATOLOGIA" TO "SISNET";

 -- Conceder permissões para o usuário SISNET nas views

  GRANT INSERT ON "AGE"."CAMP_ODONTO_APARELHO" TO "SISNET"
  GRANT SELECT ON "AGE"."CAMP_ODONTO_APARELHO" TO "SISNET"
  GRANT UPDATE ON "AGE"."CAMP_ODONTO_APARELHO" TO "SISNET"
  GRANT SELECT ON "AGE"."VIEW_CAMP_ODONTO_APARELHO" TO "SISNET"




CREATE TABLE AGE.CAMP_ODONTO_APARELHO (
  SEQ_CAMPANHA      NUMBER (10),
  COD_PACIENTE      NUMBER(10),
  NOME_PACIENTE     VARCHAR2(100),
  FONE              VARCHAR2(20),
  LIGAR_EM          DATE,
  STATUS            VARCHAR2(20),
  TEMPO_LIGACAO     NUMBER(5),
  CANAIS             NUMBER(3),
  CAMPANHA          VARCHAR2(60)
);


-- AGE.VIEW_CAMP_ODONTO_APARELHO fonte

CREATE OR REPLACE FORCE VIEW "AGE"."VIEW_CAMP_ODONTO_APARELHO" ("SEQ_CAMPANHA", "NOME_PACIENTE", "FONE", "CAMPANHA") AS 
  (SELECT 
		SEQ_CAMPANHA,
		NOME_PACIENTE,
		FONE,
		CAMPANHA
	FROM CAMP_ODONTO_APARELHO
	WHERE 
		LIGAR_EM = trunc(sysdate) AND
		STATUS = 'Enviar'
	);

GRANT SELECT ON "AGE"."VIEW_CAMP_ODONTO_APARELHO" TO "CONTROL";
GRANT SELECT ON "AGE"."VIEW_CAMP_ODONTO_APARELHO" TO "SISNET";
GRANT INSERT ON "AGE"."VIEW_CAMP_ODONTO_APARELHO" TO "SISNET";
GRANT UPDATE ON "AGE"."VIEW_CAMP_ODONTO_APARELHO" TO "SISNET";




 SELECT * FROM CAMPANHAS_VOIP_BASE C
 WHERE 1=1
 AND C.NOME_CAMP <>'CHECKUP MULHER' -- 
 AND C.NOME_CAMP <>'CHECKUP HOMEM' -- 
 AND C.NOME_CAMP <>'CARDIOLOGIA' -- 
 AND C.NOME_CAMP <>'CHECK UP SAÚDE' -- 
 AND C.NOME_CAMP <>'OFTALMOLOGIA' -- 
 AND C.NOME_CAMP <>'ODONTO GERAL'
 AND C.NOME_CAMP <>'ODONTO' 
 AND C.NOME_CAMP <>'PSICOLOGIA E PSIQUIATRIA'
;


SELECT * FROM DADOS_CALENDARIO_BI dc
WHERE dc.MES_AJUSTADO = '01/09/2025';

     SELECT * FROM DADOS_CALENDARIO_BI dc
WHERE dc.MES_AJUSTADO = '01/09/2025'
AND dc.DATA >= '17/09/2025';

---------------------------------------------
SELECT * FROM CAMP_CARDIOLOGIA c        -- OK
ORDER BY c.LIGAR_EM  ASC;
---------------------------------------------
SELECT * FROM CAMP_CHECKUP_MULHER c     -- OK
ORDER BY c.LIGAR_EM  ASC;
---------------------------------------------
SELECT * FROM CAMP_CHECKUP_SAUDE c      -- OK
ORDER BY c.LIGAR_EM  ASC;
---------------------------------------------
SELECT * FROM CAMP_OFTALMOLOGIA c       -- OK
ORDER BY c.LIGAR_EM  ASC; 
---------------------------------------------
SELECT * FROM CAMP_PSICO_PSIQUI c       -- OK
ORDER BY c.LIGAR_EM  ASC; 
---------------------------------------------
SELECT * FROM CAMP_ODONTO c            --  OK
ORDER BY c.LIGAR_EM  ASC; 
---------------------------------------------
SELECT * FROM CAMP_ODONTO_GERAL c       -- OK
ORDER BY c.LIGAR_EM  ASC; 
---------------------------------------------
SELECT * FROM CAMP_DERMATOLOGIA  c      -- OK
ORDER BY c.LIGAR_EM  ASC; 
---------------------------------------------
SELECT * FROM CAMP_CHECKUP_HOMEM c     --  XX
ORDER BY c.LIGAR_EM  ASC; 
---------------------------------------------

-- CAMP_CARDIOLOGIA
SELECT c.*, COUNT(*) OVER () AS TOTAL_REGISTROS
FROM CAMP_CARDIOLOGIA c
WHERE TO_CHAR(c.LIGAR_EM, 'MM/YYYY') = '10/2025'
ORDER BY c.LIGAR_EM ASC;

-- CAMP_CHECKUP_MULHER
SELECT c.*, COUNT(*) OVER () AS TOTAL_REGISTROS
FROM CAMP_CHECKUP_MULHER c
WHERE TO_CHAR(c.LIGAR_EM, 'MM/YYYY') = '10/2025'
ORDER BY c.LIGAR_EM ASC;

-- CAMP_CHECKUP_SAUDE
SELECT c.*, COUNT(*) OVER () AS TOTAL_REGISTROS
FROM CAMP_CHECKUP_SAUDE c
WHERE TO_CHAR(c.LIGAR_EM, 'MM/YYYY') = '10/2025'
ORDER BY c.LIGAR_EM ASC;

-- CAMP_OFTALMOLOGIA
SELECT c.*, COUNT(*) OVER () AS TOTAL_REGISTROS
FROM CAMP_OFTALMOLOGIA c
WHERE TO_CHAR(c.LIGAR_EM, 'MM/YYYY') = '10/2025'
ORDER BY c.LIGAR_EM ASC;

-- CAMP_PSICO_PSIQUI
SELECT c.*, COUNT(*) OVER () AS TOTAL_REGISTROS
FROM CAMP_PSICO_PSIQUI c
WHERE TO_CHAR(c.LIGAR_EM, 'MM/YYYY') = '10/2025'
ORDER BY c.LIGAR_EM ASC;

-- CAMP_ODONTO
SELECT c.*, COUNT(*) OVER () AS TOTAL_REGISTROS
FROM CAMP_ODONTO c
WHERE TO_CHAR(c.LIGAR_EM, 'MM/YYYY') = '10/2025'
ORDER BY c.LIGAR_EM ASC;

-- CAMP_ODONTO_GERAL
SELECT c.*, COUNT(*) OVER () AS TOTAL_REGISTROS
FROM CAMP_ODONTO_GERAL c
WHERE TO_CHAR(c.LIGAR_EM, 'MM/YYYY') = '10/2025'
ORDER BY c.LIGAR_EM ASC;

-- CAMP_DERMATOLOGIA
SELECT c.*, COUNT(*) OVER () AS TOTAL_REGISTROS
FROM CAMP_DERMATOLOGIA c
WHERE TO_CHAR(c.LIGAR_EM, 'MM/YYYY') = '10/2025'
ORDER BY c.LIGAR_EM ASC;

-- CAMP_CHECKUP_HOMEM
SELECT c.*, COUNT(*) OVER () AS TOTAL_REGISTROS
FROM CAMP_CHECKUP_HOMEM c
WHERE TO_CHAR(c.LIGAR_EM, 'MM/YYYY') = '10/2025'
ORDER BY c.LIGAR_EM ASC;
-----------------------------------------------
/*

DELETE  CAMP_CHECKUP_MULHER
WHERE CAMPANHA = 'CHECKUP MULHER';
COMMIT;

*/
--------------------------------------------
SELECT * FROM VIEW_CAMP_CARDIOLOGIA;
SELECT * FROM VIEW_CAMP_CHECKUP_SAUDE;
SELECT * FROM VIEW_CAMP_CHECKUP_HOMEM;
SELECT * FROM VIEW_CAMP_CHECKUP_MULHER;
SELECT * FROM VIEW_CAMP_ODONTO;
SELECT * FROM VIEW_CAMP_OFTALMOLOGIA;
SELECT * FROM VIEW_CAMP_PSICO_PSIQUI;
SELECT * FROM VIEW_CAMP_ODONTO_GERAL;
--------------------------------------------


SELECT * FROM CAMP_CARDIOLOGIA
WHERE STATUS <> 'Enviar'
UNION ALL
SELECT * FROM CAMP_CHECKUP_MULHER
WHERE STATUS <> 'Enviar'
UNION ALL
SELECT * FROM CAMP_CHECKUP_SAUDE
WHERE STATUS <> 'Enviar'
UNION ALL
SELECT * FROM CAMP_OFTALMOLOGIA
WHERE STATUS <> 'Enviar'
UNION ALL
SELECT * FROM CAMP_PSICO_PSIQUI
WHERE STATUS <> 'Enviar'
UNION ALL
SELECT * FROM CAMP_CHECKUP_HOMEM  
WHERE STATUS <> 'Enviar'
UNION ALL
SELECT * FROM CAMP_ODONTO
WHERE STATUS <> 'Enviar'
UNION ALL
SELECT * FROM CAMP_ODONTO_GERAL
WHERE STATUS <> 'Enviar'
;


------------------------------------------------------------------------------------------
-- REMOVER DUPLICADOS COM TEMPO_LIGACAO NULO'

DELETE FROM CAMP_DERMATOLOGIA
WHERE SEQ_CAMPANHA IN (
    WITH BASE_AJUST AS (
        SELECT 
            SEQ_CAMPANHA,
            ROW_NUMBER() OVER (
                PARTITION BY CAMPANHA, COD_PACIENTE, REGEXP_REPLACE(FONE, '[^0-9]', '')
                ORDER BY LIGAR_EM ASC, TEMPO_LIGACAO DESC
            ) AS rn,
            COUNT(*) OVER (
                PARTITION BY CAMPANHA, COD_PACIENTE, REGEXP_REPLACE(FONE, '[^0-9]', '')
            ) AS qtd_duplicados,
            TEMPO_LIGACAO
        FROM CAMP_DERMATOLOGIA
        WHERE TO_CHAR(LIGAR_EM, 'MM/YYYY') = '10/2025'
    )
    SELECT SEQ_CAMPANHA
    FROM BASE_AJUST
    WHERE rn = 1
      AND qtd_duplicados > 1
      AND TEMPO_LIGACAO IS NULL
);
commit;
------------------------------------------------------------------------------------------
  -- VEMOS SE TEM DUPLICADOS
       
        SELECT 
            SEQ_CAMPANHA,
            STATUS,
            ROW_NUMBER() OVER (
                PARTITION BY CAMPANHA, COD_PACIENTE, REGEXP_REPLACE(FONE, '[^0-9]', '')
                ORDER BY LIGAR_EM ASC, TEMPO_LIGACAO DESC
            ) AS rn,
            COUNT(*) OVER (
                PARTITION BY CAMPANHA, COD_PACIENTE, REGEXP_REPLACE(FONE, '[^0-9]', '')
            ) AS qtd_duplicados,
            TEMPO_LIGACAO
        FROM CAMP_DERMATOLOGIA   -----------------------
        WHERE TO_CHAR(LIGAR_EM, 'MM/YYYY') = '10/2025'
         ORDER BY FONE ASC;             
------------------------------------------------------------------------------------------
-- VEMOS OS STATUS PARA AJUSTARc  -- NÃ£o completou
    SELECT * FROM  CAMP_DERMATOLOGIA   
        WHERE TO_CHAR(LIGAR_EM, 'MM/YYYY') = '10/2025'
          AND TEMPO_LIGACAO > 0
          AND STATUS = 'Enviar'
          ORDER BY FONE ASC;
          
    SELECT * FROM  CAMP_DERMATOLOGIA 
        WHERE TO_CHAR(LIGAR_EM, 'MM/YYYY') = '10/2025'
          AND TEMPO_LIGACAO = 0
         AND STATUS = 'Enviar'
          ORDER BY FONE ASC;
          
          
    UPDATE CAMP_DERMATOLOGIA set STATUS = 'Completou' 
          WHERE TO_CHAR(LIGAR_EM, 'MM/YYYY') = '10/2025'
          AND TEMPO_LIGACAO > 0
          AND STATUS = 'Enviar';
          
    UPDATE CAMP_DERMATOLOGIA set STATUS = 'Nao completou' 
          WHERE TO_CHAR(LIGAR_EM, 'MM/YYYY') = '10/2025'
          AND TEMPO_LIGACAO = 0
          AND STATUS = 'Enviar';
          
    UPDATE CAMP_DERMATOLOGIA set STATUS = 'Nao completou' 
          WHERE TO_CHAR(LIGAR_EM, 'MM/YYYY') = '10/2025'
          AND STATUS = 'NÃ£o completou';
          
------------------------------------------------------------------------------------------

SELECT
  (SELECT COUNT(*) FROM CAMP_CARDIOLOGIA WHERE TO_CHAR(LIGAR_EM, 'MM/YYYY') = '10/2025')     AS CARDIOLOGIA,
  (SELECT COUNT(*) FROM CAMP_CHECKUP_MULHER WHERE TO_CHAR(LIGAR_EM, 'MM/YYYY') = '10/2025')  AS CHECKUP_MULHER,
  (SELECT COUNT(*) FROM CAMP_CHECKUP_SAUDE WHERE TO_CHAR(LIGAR_EM, 'MM/YYYY') = '10/2025')   AS CHECKUP_SAUDE,
  (SELECT COUNT(*) FROM CAMP_OFTALMOLOGIA WHERE TO_CHAR(LIGAR_EM, 'MM/YYYY') = '10/2025')    AS OFTALMOLOGIA,
  (SELECT COUNT(*) FROM CAMP_PSICO_PSIQUI WHERE TO_CHAR(LIGAR_EM, 'MM/YYYY') = '10/2025')    AS PSICO_PSIQUI,
  (SELECT COUNT(*) FROM CAMP_CHECKUP_HOMEM WHERE TO_CHAR(LIGAR_EM, 'MM/YYYY') = '10/2025')   AS CHECKUP_HOMEM,
  (SELECT COUNT(*) FROM CAMP_DERMATOLOGIA WHERE TO_CHAR(LIGAR_EM, 'MM/YYYY') = '10/2025')    AS DERMATOLOGIA,
  (SELECT COUNT(*) FROM CAMP_ORTODONTIA WHERE TO_CHAR(LIGAR_EM, 'MM/YYYY') = '10/2025')      AS ORTO,
  (SELECT COUNT(*) FROM CAMP_ODONTO WHERE TO_CHAR(LIGAR_EM, 'MM/YYYY') = '10/2025')          AS ODONTO,
  (SELECT COUNT(*) FROM CAMP_ODONTO_GERAL WHERE TO_CHAR(LIGAR_EM, 'MM/YYYY') = '10/2025')    AS ODONTO_GERAL,
  (SELECT COUNT(*) FROM CAMP_ANIVERSARIANTES WHERE TO_CHAR(LIGAR_EM, 'MM/YYYY') = '10/2025') AS ANIVER
FROM DUAL;
